version: "3"
services:
  web:
    build: "./app"
    ports:
      - "5000:5000"
    volumes:
      - /home/qipz/projects/webdev/python/docker-files/metabolic-syndrome:/app
    environment:
      - NAME=Test
